### ISSUE TITLE
how to make the list appear above all views

### ISSUE THREAD

**Issue by gerard0315** [bulenttastan/react-native-list-popover#17]
Hi I have three of the components together and there is an awkward overlay between them, is there any solution to this?

**Comment by GedoonS** [comment]
I tried a few things but eventually ended not using this component. If you can update your RN to 0.29, do that and then use [zIndex](http://facebook.github.io/react-native/releases/0.29/docs/layout-props.html#zindex) to pop the list over other components. I'm pretty much stuck with older RN at this point so updating wasn't an option for me at this time. I also tried to use a module called [Overlay](https://github.com/brentvatne/react-native-overlay) that supposedly does the same thing for older versions of RN, but the problem with that was that I wasn't able to activate any onPress events in the list, and the positioning became absolute instead of relative so that wasn't such a good idea either...

My eventual solution was to loose the popover entirely and use native [Modal](https://facebook.github.io/react-native/docs/modal.html) and [PickerIOS](https://facebook.github.io/react-native/docs/pickerios.html) to display a picker component on the bottom of the view. In my opinion this was more iOS way of doing it rather than using a popover.

**Comment by x-bingxin** [comment]
@GedoonS  With latest RN version 0.43, this issue show up as well, I tried to use the **zIndex** in style, still not work.  Your solution has inspired me, thanks : )

**Comment by bulenttastan** [comment]
Fixed in commit https://github.com/bulenttastan/react-native-list-popover/commit/2e7cde697505a9325ea332f014869c91292b5fea
